CREATE TABLE USERS (
   id INTEGER NOT NULL ,
   username CHARACTER VARYING (50) NOT NULL ,
   password CHARACTER VARYING (100)  ,
   firstname CHARACTER VARYING (50),
   lastname CHARACTER VARYING (50),
   email CHARACTER VARYING(50),
   age INTEGER,
   status BOOLEAN  DEFAULT 1
);

CREATE SEQUENCE USERS_ID_SEQ start with 1 INCREMENT by 1;
ALTER TABLE ONLY USERS ALTER COLUMN ID SET DEFAULT nextval('USERS_ID_SEQ'::regclass);
ALTER TABLE ONLY USERS ADD CONSTRAINT USERS_PKEY PRIMARY KEY (ID);