CREATE TABLE TICKETS (
   ID INTEGER NOT NULL ,
   NAME CHARACTER VARYING (30) NOT NULL ,
   USER_ID INTEGER NOT NULL ,
);

CREATE SEQUENCE TICKETS_ID_SEQ start with 1 INCREMENT by 1;
ALTER TABLE ONLY TICKETS ALTER COLUMN ID SET DEFAULT nextval('TICKETS_ID_SEQ'::regclass);
ALTER TABLE ONLY TICKETS ADD CONSTRAINT TICKETS_PKEY PRIMARY KEY (ID);